# Spring data Source
Spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/?userSSL=false&allowPuvlicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Kim00468?
    driver-class-name: com.mysql.cj.jdbc.Driver

